// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0egwVGHbLhgZ1DYV4dDPkPry-shjoUA',
    appId: '1:493647782333:web:58de145d23adca72bcf2d4',
    messagingSenderId: '493647782333',
    projectId: 'auth-f4485',
    authDomain: 'auth-f4485.firebaseapp.com',
    storageBucket: 'auth-f4485.appspot.com',
    measurementId: 'G-TZ9TNRLV1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAncRrj4E7o4dwYUbTbW9DfeLXgpcvMT98',
    appId: '1:493647782333:android:be70b35dc9982037bcf2d4',
    messagingSenderId: '493647782333',
    projectId: 'auth-f4485',
    storageBucket: 'auth-f4485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3W3clcjrBwnlIiVStpKziVzZC9a8TT70',
    appId: '1:493647782333:ios:462f3eef8d603bc4bcf2d4',
    messagingSenderId: '493647782333',
    projectId: 'auth-f4485',
    storageBucket: 'auth-f4485.appspot.com',
    iosClientId: '493647782333-o6svt13oij4e2jqthkkir5qhf87pe8ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorisedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3W3clcjrBwnlIiVStpKziVzZC9a8TT70',
    appId: '1:493647782333:ios:462f3eef8d603bc4bcf2d4',
    messagingSenderId: '493647782333',
    projectId: 'auth-f4485',
    storageBucket: 'auth-f4485.appspot.com',
    iosClientId: '493647782333-o6svt13oij4e2jqthkkir5qhf87pe8ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorisedApp',
  );
}
